In [1]:
import networkx as nx
from node2vec import Node2Vec
import json
import re
import matplotlib.pyplot as plt
from tqdm import tqdm
from random import choice
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from keras.models import Sequential
from keras.layers import Dense
from keras import backend as K

paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress
Using TensorFlow backend.


In [2]:
def recall(y_true, y_pred):
    """Recall metric.

    Only computes a batch-wise average of recall.

    Computes the recall, a metric for multi-label classification of
    how many relevant items are selected.
    """
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall


def precision(y_true, y_pred):
    """Precision metric.

    Only computes a batch-wise average of precision.

    Computes the precision, a metric for multi-label classification of
    how many selected items are relevant.
    """
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision


def authors_to_emb(authors, embs):
    try:
        out = list(embs[authors[0]])
        out.extend(list(embs[authors[1]]))
        return out
    except:
        return None


def all_coauthors_pairs(coauthors, exception_graph=None):
    if len(coauthors) < 2:
        return None
    pairs = []
    for i in range(len(coauthors)):
        for j in range(len(coauthors[i + 1:])):
            if exception_graph:
                try:
                    dist = nx.shortest_path_length(graph, coauthors[i], coauthors[i + j + 1])
                except:
                    dist = 100
                if dist != 1:
                    pairs.append([coauthors[i], coauthors[i + j + 1]])
            else:
                pairs.append([coauthors[i], coauthors[i + j + 1]])
    return pairs


def random_not_coauthors(graph, need_num, authors):
    pairs = []
    for _ in range(need_num * 4):
        a1 = choice(list(graph.nodes()))
        a2 = choice(list(graph.nodes()))
        
        try:
            dist = nx.shortest_path_length(graph, a1, a2)
        except:
            dist = 100
        if (not a1 == a2) and (dist > 1) and (a1 in authors) and (a2 in authors):
            pairs.append([a1, a2])
        if len(pairs) >= need_num:
            break
    return pairs

In [3]:
with open('arxivData.json') as json_data:
    dataset = json.load(json_data)
    json_data.close()

In [4]:
graph = nx.Graph()
authors = set([])
X_train_val = []
y_train_val = []
for paper in dataset:
    if 2014 <= paper['year'] <= 2016:
        try:
            paper_authors = []
            for author in json.loads(re.sub("'", '"', paper['author'])):
                paper_authors.append(author['name'])
            if len(paper_authors) > 1:
                authors.update(paper_authors)
            coauthors = all_coauthors_pairs(paper_authors)
            for pair in coauthors:
                graph.add_edge(pair[0], pair[1])
            X_train_val.extend(coauthors)
        except:
            pass


data_size = len(X_train_val)
X_train_val.extend(random_not_coauthors(graph, data_size * 1, authors))

y_train_val = [[0.0, 1.0]] * data_size
y_train_val.extend([[1.0, 0.0]] * (len(X_train_val) - data_size))

In [5]:
graph_test = nx.Graph()
X_test = []
y_test = []
for paper in dataset:
    if paper['year'] >= 2017:
        try:
            paper_authors = []
            for author in json.loads(re.sub("'", '"', paper['author'])):
                if author['name'] in authors:
                    paper_authors.append(author['name'])
            coauthors = all_coauthors_pairs(paper_authors)
            for pair in coauthors:
                graph_test.add_edge(pair[0], pair[1])
            X_test.extend(all_coauthors_pairs(paper_authors, graph))
        except:
            pass


data_size = len(X_test)
X_test.extend(random_not_coauthors(graph_test, data_size*5, authors))

y_test = [[0.0, 1.0]] * data_size
y_test.extend([[1.0, 0.0]] * (len(X_test) - data_size))

X_test_raw = X_test
y_test_raw = y_test

In [6]:
mask_valid = [(pair[0] in authors and pair[1] in authors) for pair in X_test_raw]

In [7]:
X_test_valid = list(np.array(X_test_raw)[mask_valid])
y_test_valid = list(np.array(y_test_raw)[mask_valid])

In [8]:
preds_nx = [pred for _, _, pred in nx.jaccard_coefficient(graph, [x for x in X_test_raw])]

y_test = [np.argmax(y) for y in np.array(y_test_raw)]

y_pred = [1 if pred >= 0.5 else 0 for pred in preds_nx]
print(classification_report(y_test, y_pred))
print('\n')
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test, preds_nx))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91     69435
           1       0.96      0.00      0.01     13887

   micro avg       0.83      0.83      0.83     83322
   macro avg       0.90      0.50      0.46     83322
weighted avg       0.86      0.83      0.76     83322



[[69433     2]
 [13832    55]]
0.5989206589127878


In [9]:
# print('Generate walks')
node2vec = Node2Vec(graph, dimensions=20, walk_length=16, num_walks=10, workers=10)

Computing transition probabilities: 100%|██████████| 24475/24475 [00:08<00:00, 2930.96it/s]


In [10]:
print('Learn embeddings')
embs = node2vec.fit(window=10, min_count=1)

Learn embeddings


In [11]:
model = Sequential()
model.add(Dense(40))
model.add(Dense(30, activation='tanh'))
model.add(Dense(20, activation='relu'))
# model.add(Dense(10, activation='exponential'))  ### Вот этот слой лишний. Возможно активация не очень.
model.add(Dense(2, activation='softmax'))
model.compile(loss="categorical_crossentropy", optimizer='rmsprop', metrics=["accuracy"])

Instructions for updating:
Colocations handled automatically by placer.


In [12]:
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.2, random_state=42)
X_train = np.array([authors_to_emb(pair, embs) for pair in X_train])
y_train = np.array(y_train)
X_val = np.array([authors_to_emb(pair, embs) for pair in X_val])
y_val = np.array(y_val)
model.fit(X_train, y_train, batch_size=128, epochs=40, validation_data=(X_val, y_val))

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:32: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


Instructions for updating:
Use tf.cast instead.
Train on 126310 samples, validate on 31578 samples
Epoch 1/40
126310/126310 [==============================] - 1s 10us/step - loss: 0.2595 - acc: 0.8954 - val_loss: 0.1410 - val_acc: 0.9492
Epoch 2/40
126310/126310 [==============================] - 1s 8us/step - loss: 0.1187 - acc: 0.9564 - val_loss: 0.1056 - val_acc: 0.9612
Epoch 3/40
126310/126310 [==============================] - 1s 8us/step - loss: 0.0899 - acc: 0.9680 - val_loss: 0.0850 - val_acc: 0.9692
Epoch 4/40
126310/126310 [==============================] - 1s 9us/step - loss: 0.0758 - acc: 0.9729 - val_loss: 0.0797 - val_acc: 0.9720
Epoch 5/40
126310/126310 [==============================] - 1s 9us/step - loss: 0.0673 - acc: 0.9762 - val_loss: 0.0821 - val_acc: 0.9704
Epoch 6/40
126310/126310 [==============================] - 1s 8us/step - loss: 0.0613 - acc: 0.9782 - val_loss: 0.0707 - val_acc: 0.9765
Epoch 7/40
126310/126310 [==============================] - 1s 8us/step 

In [13]:
# 1 - соавторы, 0 - нет
#               precision    recall  f1-score   support

#            0       0.99      0.99      0.99     15866
#            1       0.99      0.99      0.99     15712

#    micro avg       0.99      0.99      0.99     31578
#    macro avg       0.99      0.99      0.99     31578
# weighted avg       0.99      0.99      0.99     31578
# [[15652   214]
#  [  155 15557]]
# 0.9989353879890981


y_pred = [np.argmax(y) for y in model.predict(X_val)]
y_true = [np.argmax(y) for y in y_val]
print(classification_report(y_true, y_pred))
print('\n')
print(confusion_matrix(y_true, y_pred))
print(roc_auc_score(y_true, [proba[1] for proba in model.predict(X_val)]))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     15866
           1       0.98      0.99      0.99     15712

   micro avg       0.99      0.99      0.99     31578
   macro avg       0.99      0.99      0.99     31578
weighted avg       0.99      0.99      0.99     31578



[[15629   237]
 [  200 15512]]
0.9985027694550053


In [14]:
# nx.resource_allocation_index
#               precision    recall  f1-score   support
#            0       0.83      1.00      0.91     69435
#            1       0.76      0.00      0.00     13887

#    micro avg       0.83      0.83      0.83     83322
#    macro avg       0.80      0.50      0.46     83322
# weighted avg       0.82      0.83      0.76     83322
# [[69429     6]
#  [13868    19]]
# 0.5990594303456509

# nx.jaccard_coefficient 
#               precision    recall  f1-score   support

#            0       0.83      1.00      0.91     69435
#            1       1.00      0.00      0.01     13887

#    micro avg       0.83      0.83      0.83     83322
#    macro avg       0.92      0.50      0.46     83322
# weighted avg       0.86      0.83      0.76     83322
# [[69435     0]
#  [13832    55]]
# 0.5990585638635837


# 1*1 Logreg
#               precision    recall  f1-score   support

#            0       0.86      0.99      0.92     69353
#            1       0.83      0.19      0.31     13887

#    micro avg       0.86      0.86      0.86     83240
#    macro avg       0.84      0.59      0.62     83240
# weighted avg       0.85      0.86      0.82     83240
# [[68812   541]
#  [11241  2646]]
# 0.6395078283412827

# 5*1 All_pairs
#               precision    recall  f1-score   support

#            0       0.92      0.98      0.95    135084
#            1       0.84      0.59      0.69     27216

#    micro avg       0.91      0.91      0.91    162300
#    macro avg       0.88      0.78      0.82    162300
# weighted avg       0.91      0.91      0.91    162300
# [[132044   3040]
#  [ 11130  16086]]

# 5*1 New pairs
#               precision    recall  f1-score   support

#            0       0.87      0.98      0.92     69367
#            1       0.68      0.24      0.35     13887

#    micro avg       0.85      0.85      0.85     83254
#    macro avg       0.77      0.61      0.64     83254
# weighted avg       0.83      0.85      0.82     83254
# [[67779  1588]
#  [10569  3318]]
# 0.6553634735001194

# Random
#              precision    recall  f1-score   support

#            0       1.00      0.79      0.88     83254
#            1       0.00      0.00      0.00         0

#    micro avg       0.79      0.79      0.79     83254
#    macro avg       0.50      0.39      0.44     83254
# weighted avg       1.00      0.79      0.88     83254
# [[65546 17708]
#  [    0     0]]

# 1*1 New pairs
#               precision    recall  f1-score   support

#            0       0.87      0.95      0.91     69353
#            1       0.55      0.29      0.38     13887

#    micro avg       0.84      0.84      0.84     83240
#    macro avg       0.71      0.62      0.65     83240
# weighted avg       0.82      0.84      0.82     83240
# [[66055  3298]
#  [ 9823  4064]]
# 0.6657878721401573

# 1*1 New pairs Stack more layers 40e
#               precision    recall  f1-score   support

#            0       0.87      0.96      0.91     69341
#            1       0.59      0.30      0.39     13887

#    micro avg       0.85      0.85      0.85     83228
#    macro avg       0.73      0.63      0.65     83228
# weighted avg       0.82      0.85      0.83     83228
# [[66511  2830]
#  [ 9789  4098]]
# 0.7027983388267736

# 1*1 New pairs Stack MORE layers 40e
#               precision    recall  f1-score   support

#            0       0.87      0.97      0.92     69341
#            1       0.64      0.27      0.38     13887

#    micro avg       0.85      0.85      0.85     83228
#    macro avg       0.75      0.62      0.65     83228
# weighted avg       0.83      0.85      0.83     83228
# [[67246  2095]
#  [10151  3736]]
# 0.6888330186522706

mask_valid = [np.array(authors_to_emb(pair, embs)).shape == (40,) for pair in X_test_raw]
X_test = np.array([authors_to_emb(pair, embs) for pair in X_test_raw
                   if np.array(authors_to_emb(pair, embs)).shape == (40,)])
y_test = np.array(y_test_raw)[mask_valid]
y_pred = [np.argmax(y) for y in model.predict(X_test)]
y_true = [np.argmax(y) for y in y_test]
print(classification_report(y_true, y_pred))
print('\n')
print(confusion_matrix(y_true, y_pred))
print(roc_auc_score(y_true, [proba[1] for proba in model.predict(X_test)]))

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:32: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


              precision    recall  f1-score   support

           0       0.87      0.97      0.91     69435
           1       0.61      0.27      0.37     13887

   micro avg       0.85      0.85      0.85     83322
   macro avg       0.74      0.62      0.64     83322
weighted avg       0.82      0.85      0.82     83322



[[67018  2417]
 [10184  3703]]
0.6937477277855997


In [15]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.linear_model import LogisticRegression

X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.2, random_state=42)
X_train = np.array([cosine_similarity(embs.wv.__getitem__(pair[0]).reshape(1, -1),
                                      embs.wv.__getitem__(pair[1]).reshape(1, -1))[0] for pair in X_train])
y_train = [np.argmax(y) for y in y_train]

In [16]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [17]:
X_val = np.array([cosine_similarity(embs.wv.__getitem__(pair[0]).reshape(1, -1),
                                      embs.wv.__getitem__(pair[1]).reshape(1, -1))[0] for pair in X_val])
y_val = [np.argmax(y) for y in y_val]

y_pred = log_reg.predict(X_val)
print(classification_report(y_val, y_pred))
print('\n')
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     15866
           1       0.99      0.99      0.99     15712

   micro avg       0.99      0.99      0.99     31578
   macro avg       0.99      0.99      0.99     31578
weighted avg       0.99      0.99      0.99     31578



[[15751   115]
 [   80 15632]]


In [18]:
X_test = np.array([cosine_similarity(embs.wv.__getitem__(pair[0]).reshape(1, -1),
                                      embs.wv.__getitem__(pair[1]).reshape(1, -1))[0] 
                   for pair in np.array(X_test_raw)[mask_valid]])
y_test = [np.argmax(y) for y in np.array(y_test_raw)[mask_valid]]

y_pred = log_reg.predict(X_test)
print(classification_report(y_test, y_pred))
print('\n')
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test, [proba[1] for proba in log_reg.predict_proba(X_test)]))

              precision    recall  f1-score   support

           0       0.86      0.99      0.92     69435
           1       0.84      0.18      0.30     13887

   micro avg       0.86      0.86      0.86     83322
   macro avg       0.85      0.59      0.61     83322
weighted avg       0.86      0.86      0.82     83322



[[68960   475]
 [11325  2562]]
0.6460888759938105
